[browser]
gatherUsageStats = false

[client]
caching = true

[global]
disableWatchdogWarning = true
showWarningOnDirectExecution = false

[server]
enableCORS = true
enableXsrfProtection = true
enableWebsocketCompression = true

[theme]
primaryColor="#BD93F9"
backgroundColor="#282A36"
secondaryBackgroundColor="#44475A"
textColor="#F8F8F2"
font="sans serif"
